feat (StatusIcon): Add StatusIcon component to Core
PlayPickUp/pickup-ui pull request #157
Opened 2021-09-13 22:46 UTC by dLars99

Created a new StatusIcon component that takes one of the pick statuses (`graded_true, graded_false, disqualified, closed` or `pending`) and returns the correct icon with appropriate color.

Closes #156

2021-09-14 02:01 UTC, erwstout requested changes
one small nit :-D

2021-09-14 10:29 UTC, denvermullets approved these changes

2021-09-14 13:45 UTC, dLars99 commented on packages/core/src/StatusIcon/StatusIcon.test.tsx
> +  //console.log({ getByTestId("statusIcon") });
🤦‍♂️

2021-09-15 13:38 UTC, denvermullets approved these changes

2021-09-15 13:47 UTC, wliederer approved these changes

2021-09-15 15:51 UTC, erwstout approved these changes

2021-09-15 16:18 UTC, merged