feat(checkbox): add checkbox to pickup ui
PlayPickUp/pickup-ui pull request #211
Opened 2021-11-01 19:58 UTC by wliederer

Made checkbox for pickup ui
playground screenshot:
![image](https://user-images.githubusercontent.com/55102812/139733350-b42274c6-82c1-4efe-96b2-6e24311a2f00.png)

added to storybook:
![image](https://user-images.githubusercontent.com/55102812/139733262-7219c58b-cfce-4915-be4c-f8a329eb726c.png)

created two tests:
1. to check to checkbox renders without crashing and matches snapshot
2. to check that prop checked=boolean can be passed and the box can be clicked and change its checked state.

2021-11-02 16:25 UTC, dLars99 requested changes
Looks good and works internally. However, right now, there's no way for the parent to see the state of the checkbox. I'm thinking it may need a handleChange or onChange prop to receive a function from the parent, maybe lifting state as well if needed.

2021-11-02 20:23 UTC, wliederer commented
> Looks good and works internally. However, right now, there's no way for the parent to see the state of the checkbox. I'm thinking it may need a handleChange or onChange prop to receive a function from the parent, maybe lifting state as well if needed.

I added a required onChange function pass that works with internal checkbox state to work with parent state.  I looked at the prop-picker when thinking of an implementation for it.  Open to other ideas wasnt really sure how to approach this one.  

Let me know what yall think

2021-11-03 13:19 UTC, dLars99 approved these changes

2021-11-03 14:12 UTC, denvermullets requested changes

2021-11-03 14:12 UTC, denvermullets commented on playground/src/App/index.tsx
> +    console.log(checked), [checked];
do we need this still?

2021-11-03 14:13 UTC, denvermullets approved these changes

2021-11-03 14:30 UTC, merged