fix(checkbox): remove unused props
PlayPickUp/pickup-ui pull request #322
Opened 2022-03-28 15:17 UTC by denvermullets

2022-03-28 16:43 UTC, KrystineJannenga submitted a review, later dismissed

2022-03-28 21:36 UTC, dLars99 requested changes
If I plug a Checkbox into Playground using the format on the Picker, it's still mad about missing the Formik props. Is there a way to make those optional?
![image](https://user-images.githubusercontent.com/54251395/160491162-706ab8c6-d2bb-4e21-9a55-f0d7cc53166b.png)
```                  
  <CheckBox
     checked={checkBoxChecked}
     onChange={() => setCheckBox(checkBoxChecked)}
  >
```

2022-04-05 19:37 UTC, denvermullets commented
> If I plug a Checkbox into Playground using the format on the Picker, it's still mad about missing the Formik props. Is there a way to make those optional? ![image](https://user-images.githubusercontent.com/54251395/160491162-706ab8c6-d2bb-4e21-9a55-f0d7cc53166b.png)
> 
> ```
>   <CheckBox
>      checked={checkBoxChecked}
>      onChange={() => setCheckBox(checkBoxChecked)}
>   >
> ```

yeah, my bad. i was extending the type from an earlier thing i was attempting (i think, been a minute). 

works with this in the form on playground:
```
                  <CheckBox
                    label={"this is a label"}
                    checked={false}
                    onChange={(event) => setChecked(event)}
                  />
```

2022-04-06 13:19 UTC, dLars99 approved these changes

2022-04-06 18:24 UTC, merged