bug(NestedInput): handleClick and pevent default possible rifx
PlayPickUp/pickup-ui pull request #86
Opened 2021-07-16 23:25 UTC by katiejonesyo

2021-07-17 18:08 UTC, erwstout requested changes
Tests are failing as well since we updated the HTML structure. From the root of the repo running `yarn test -u` will update the snapshots that are currently failing. 

Also - for everything in the UI package we should be updating the documentation (storybook folder) to add the new `handleClick` prop on the Nested Input as well as adding a test that the click function works. Take a look at `Button.test.tsx` for examples of how to do click testing.

2021-07-17 18:08 UTC, erwstout commented on packages/core/src/types/index.ts
> +  preventDefault?: boolean;
Where is this coming into play? It doesn't appear to be used

2021-07-17 18:08 UTC, erwstout commented on packages/core/src/types/index.ts
> +  preventDefault: boolean;
Where is this coming into play? It doesn't appear to be used

2021-07-17 18:08 UTC, erwstout commented on packages/core/src/types/index.ts
> +  handleClick: React.MouseEventHandler<HTMLButtonElement>;
Believe this should be optional, since in other cases we may not want to pass a handleClick function

2021-07-21 21:39 UTC, JimBurch approved these changes

2021-07-26 21:23 UTC, closed without merging